Add Work section & About section
astroboyReloaded/Portfolio-setup-and-mobile-first pull request #2
Opened 2022-12-02 17:55 UTC by astroboyReloaded

2022-12-03 05:19 UTC, binhussen requested changes
Hi @astroboyReloaded , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
- Good Job for sticking to the Figma design 👍👍, I think it is better to do the tasks according to the requirements
- kindly, check your image URL and that the image is visible.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 05:19 UTC, binhussen commented on index.html
> +          <img class="thum-img" src="/images/Project 1.jpg" alt="" />
- Kindly, check your image URL, If you are accessing the image from the same folder use `./` not `/` 👍 👍  , Please do the same for all of your image URLs 😘😘.

2022-12-03 05:19 UTC, binhussen commented on style.css
> +}
- Kindly, In order to lay out the elements of individual cardcards use Flexbox not grid according to the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md).👌👌

2022-12-03 06:19 UTC, astroboyReloaded commented
**Flex for cards & img URL rename**:

- Changed cards display to flex column.
- Renamed images to unify URL.

2022-12-03 06:37 UTC, Kamba56 approved these changes
Hi @astroboyReloaded , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] All linters passed!👏👏👏
- [x] Great use of Github workflow!👏👏👏
- [x] Descriptive PR!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 06:37 UTC, Kamba56 commented on index.html
> +        <div class="social-icons-container">
- [Optional] Consider making the list of social icons an unordered list. This is best for HTML semantics.
- Also wrap the icons in an `a` tag that links to the various social media handle. You can use:
```html
<ul>
  <li>
    <a href=""><i ></a>
  </li>
  <li>
    <a href=""><i ></a>
  </li>
</ul>
```

2022-12-03 06:37 UTC, Kamba56 commented on style.css
> +button:hover {
- [Optional] Consider adding a pressed state to your buttons to match the figma template. You can use the :active pseudo class

2022-12-03 23:58 UTC, astroboyReloaded commented on index.html
> +        <div class="social-icons-container">
Thanks for the suggestion! I did!!!

2022-12-03 23:58 UTC, astroboyReloaded commented on style.css
> +button:hover {
Sure thing!

2022-12-03 23:58 UTC, merged

2022-12-04 00:07 UTC, astroboyReloaded commented
++I've merged this branch as last reviewed. Working on suggestions++ 
_ Some details have arisen... Putting the icons in a `<ul>` is done and making `buttons` part of a link is done as well! But now I have a couple of issues with the linters; hopefully, I'll have them solved tonight and start fresh by Monday._